
server:
  port: 8686
spring:
  thymeleaf:
    prefix: classpath:/templates/
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  mvc:
    static-path-pattern: /**

  resources:
    #访问静态资源路径
    static-locations: classpath:/static/

  datasource:
    url: jdbc:mysql://localhost/project?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
mybatis:
  mapperLocations: classpath:mybatis/mapper/*.xml
  basepackage: com.project.dao
  typeAliasesPackage: com.project.entity



